from __future__ import annotations

from typing import Any
from datetime import date

import oracledb

from config import DB_CONFIG


class Database:
    def __init__(self):
        try:
            dsn = oracledb.makedsn(
                DB_CONFIG["host"],
                DB_CONFIG["port"],
                service_name=DB_CONFIG["service_name"],
            )
            self.connection = oracledb.connect(
                user=DB_CONFIG["user"],
                password=DB_CONFIG["password"],
                dsn=dsn,
            )
            self.cursor = self.connection.cursor()
            # Set Oracle date format explicitly
            self.cursor.execute("ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD'")
            self.connection.commit()
        except oracledb.DatabaseError as e:
            raise RuntimeError(f"Database connection failed: {e}")

    def close(self) -> None:
        self.cursor.close()
        self.connection.close()

    def _rows_to_dicts(self, rows: list[tuple[Any, ...]]) -> list[dict[str, Any]]:
        columns = [col[0].lower() for col in self.cursor.description or []]
        return [dict(zip(columns, row)) for row in rows]

    def _safe_drop(self, statement: str) -> None:
        try:
            self.cursor.execute(statement)
        except oracledb.DatabaseError:
            pass

    def init_oltp_schema(self) -> None:
        self._safe_drop("DROP TABLE Sales CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Products CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Customers CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Locations CASCADE CONSTRAINTS")

        self.cursor.execute(
            """
            CREATE TABLE Customers (
                customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                first_name VARCHAR2(50) NOT NULL,
                last_name VARCHAR2(50) NOT NULL,
                email VARCHAR2(100),
                phone VARCHAR2(20)
            )
            """
        )

        self.cursor.execute(
            """
            CREATE TABLE Products (
                product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                product_name VARCHAR2(100) NOT NULL,
                category VARCHAR2(50),
                price NUMBER(10,2)
            )
            """
        )

        self.cursor.execute(
            """
            CREATE TABLE Locations (
                location_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                city VARCHAR2(50),
                state VARCHAR2(50),
                country VARCHAR2(50)
            )
            """
        )

        self.cursor.execute(
            """
            CREATE TABLE Sales (
                sale_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                customer_id NUMBER REFERENCES Customers(customer_id),
                product_id NUMBER REFERENCES Products(product_id),
                location_id NUMBER REFERENCES Locations(location_id),
                sale_date DATE,
                quantity NUMBER,
                total_amount NUMBER(10,2)
            )
            """
        )

        self.connection.commit()

    def seed_sample_data(self) -> None:
        # Add 20 Customers (instead of 4)
        self.cursor.executemany(
            "INSERT INTO Customers (first_name, last_name, email, phone) VALUES (:1, :2, :3, :4)",
            [
                ("James", "Smith", "james.smith@email.com", "9001111111"),
                ("Sarah", "Johnson", "sarah.j@email.com", "9002222222"),
                ("Robert", "Brown", "rob.brown@email.com", "9003333333"),
                ("Emily", "Davis", "emily.d@email.com", "9004444444"),
                ("Michael", "Wilson", "michael.w@email.com", "9005555555"),
                ("Jessica", "Taylor", "jessica.t@email.com", "9006666666"),
                ("David", "Martinez", "david.m@email.com", "9007777777"),
                ("Ashley", "Anderson", "ashley.a@email.com", "9008888888"),
                ("Daniel", "Thomas", "daniel.t@email.com", "9009999999"),
                ("Laura", "Jackson", "laura.j@email.com", "9010000000"),
                ("Matthew", "White", "matthew.w@email.com", "9011111111"),
                ("Amanda", "Harris", "amanda.h@email.com", "9012222222"),
                ("Christopher", "Martin", "chris.m@email.com", "9013333333"),
                ("Jennifer", "Garcia", "jen.g@email.com", "9014444444"),
                ("Andrew", "Lee", "andrew.l@email.com", "9015555555"),
                ("Michelle", "Perez", "michelle.p@email.com", "9016666666"),
                ("Joseph", "Thompson", "joseph.t@email.com", "9017777777"),
                ("Lisa", "Clark", "lisa.c@email.com", "9018888888"),
                ("Ryan", "Rodriguez", "ryan.r@email.com", "9019999999"),
                ("Nicole", "Lewis", "nicole.l@email.com", "9020000000"),
            ],
        )

        # Add 15 Products (instead of 4)
        self.cursor.executemany(
            "INSERT INTO Products (product_name, category, price) VALUES (:1, :2, :3)",
            [
                ("Laptop Pro 15", "Electronics", 1200.00),
                ("Wireless Mouse", "Accessories", 25.00),
                ("Monitor 27", "Electronics", 350.00),
                ("Mechanical Keyboard", "Accessories", 90.00),
                ("USB-C Hub", "Accessories", 45.00),
                ("Webcam HD", "Electronics", 75.00),
                ("External SSD 1TB", "Storage", 110.00),
                ("RAM 16GB", "Components", 80.00),
                ("Gaming Chair", "Furniture", 320.00),
                ("Desk Lamp LED", "Furniture", 35.00),
                ("Phone Stand", "Accessories", 15.00),
                ("Screen Protector Pack", "Accessories", 12.00),
                ("HDMI Cable 2m", "Accessories", 8.00),
                ("Power Bank 20000mAh", "Electronics", 50.00),
                ("Wireless Earbuds", "Electronics", 120.00),
            ],
        )

        # Add 6 Locations (instead of 3)
        self.cursor.executemany(
            "INSERT INTO Locations (city, state, country) VALUES (:1, :2, :3)",
            [
                ("New York", "NY", "USA"),
                ("Los Angeles", "CA", "USA"),
                ("Chicago", "IL", "USA"),
                ("Houston", "TX", "USA"),
                ("Phoenix", "AZ", "USA"),
                ("Miami", "FL", "USA"),
            ],
        )

        # Add 50+ Sales transactions (instead of 5)
        sales_data = [
            (1, 1, 1, "2025-01-05", 2, 2400.00),
            (2, 2, 2, "2025-01-10", 5, 125.00),
            (3, 1, 3, "2025-02-12", 1, 1200.00),
            (4, 3, 1, "2025-03-20", 2, 700.00),
            (1, 4, 2, "2025-04-03", 3, 270.00),
            (1, 5, 3, "2025-01-15", 2, 90.00),
            (2, 6, 1, "2025-01-22", 1, 75.00),
            (3, 7, 2, "2025-02-01", 4, 180.00),
            (4, 8, 3, "2025-02-14", 2, 160.00),
            (1, 9, 1, "2025-03-03", 1, 320.00),
            (2, 10, 2, "2025-03-15", 3, 105.00),
            (3, 11, 3, "2025-04-01", 1, 15.00),
            (4, 12, 1, "2025-04-10", 5, 60.00),
            (1, 13, 2, "2025-04-20", 2, 16.00),
            (2, 14, 3, "2025-05-05", 4, 200.00),
            (3, 15, 1, "2025-05-12", 3, 360.00),
            (4, 1, 2, "2025-05-18", 1, 1200.00),
            (1, 2, 3, "2025-05-25", 2, 50.00),
            (2, 3, 1, "2025-06-02", 1, 350.00),
            (3, 4, 2, "2025-06-08", 3, 270.00),
            (4, 5, 3, "2025-06-15", 2, 90.00),
            (1, 6, 1, "2025-06-22", 4, 300.00),
            (2, 7, 2, "2025-07-01", 2, 90.00),
            (3, 8, 3, "2025-07-08", 1, 80.00),
            (4, 9, 1, "2025-07-15", 3, 105.00),
            (1, 10, 2, "2025-07-20", 2, 70.00),
            (2, 11, 3, "2025-08-01", 1, 15.00),
            (3, 12, 1, "2025-08-10", 5, 60.00),
            (4, 13, 2, "2025-08-18", 2, 16.00),
            (1, 14, 3, "2025-08-25", 3, 150.00),
            (2, 15, 1, "2025-09-02", 2, 240.00),
            (3, 1, 2, "2025-09-10", 1, 1200.00),
            (4, 2, 3, "2025-09-15", 2, 50.00),
            (1, 3, 1, "2025-09-20", 1, 350.00),
            (2, 4, 2, "2025-09-28", 4, 360.00),
            (3, 5, 3, "2025-10-05", 3, 135.00),
            (4, 6, 1, "2025-10-12", 2, 150.00),
            (1, 7, 2, "2025-10-19", 1, 110.00),
            (2, 8, 3, "2025-10-26", 2, 160.00),
            (3, 9, 1, "2025-11-02", 2, 250.00),
            (4, 10, 2, "2025-11-09", 1, 35.00),
            (1, 11, 3, "2025-11-15", 2, 30.00),
            (2, 12, 1, "2025-11-22", 3, 36.00),
            (3, 13, 2, "2025-11-28", 1, 8.00),
            (4, 14, 3, "2025-12-05", 5, 250.00),
            (1, 15, 1, "2025-12-12", 2, 240.00),
            (2, 1, 2, "2025-12-18", 1, 1200.00),
            (3, 2, 3, "2025-12-24", 3, 75.00),
            (4, 3, 1, "2025-12-30", 1, 350.00),
            (1, 4, 2, "2026-01-05", 2, 180.00),
            (2, 5, 3, "2026-01-12", 1, 45.00),
        ]
        
        # Use TO_DATE with bound parameters
        self.cursor.executemany(
            "INSERT INTO Sales (customer_id, product_id, location_id, sale_date, quantity, total_amount) VALUES (:1, :2, :3, TO_DATE(:4, 'YYYY-MM-DD'), :5, :6)",
            sales_data,
        )

        self.connection.commit()

    def initialize_database(self) -> None:
        try:
            self.init_oltp_schema()
            self.seed_sample_data()
        except Exception as e:
            self.connection.rollback()
            raise RuntimeError(f"Database initialization failed: {e}")

    def create_phase3_dimensions(self) -> None:
        self._safe_drop("DROP TABLE Sales_Fact CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Customer_Dim CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Product_Dim CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Location_Dim CASCADE CONSTRAINTS")
        self._safe_drop("DROP TABLE Date_Dim CASCADE CONSTRAINTS")

        # Create Date Dimension
        self.cursor.execute(
            """
            CREATE TABLE Date_Dim (
                date_id NUMBER PRIMARY KEY,
                full_date DATE,
                year NUMBER,
                quarter NUMBER,
                month NUMBER,
                day_of_week VARCHAR2(20),
                is_weekend VARCHAR2(1)
            )
            """
        )

        # Create Customer Dimension with enriched attributes
        self.cursor.execute(
            """
            CREATE TABLE Customer_Dim (
                customer_dim_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                customer_id NUMBER,
                first_name VARCHAR2(50),
                last_name VARCHAR2(50),
                email VARCHAR2(100),
                phone VARCHAR2(20),
                customer_level VARCHAR2(20)
            )
            """
        )

        # Create Product Dimension with enriched attributes
        self.cursor.execute(
            """
            CREATE TABLE Product_Dim (
                product_dim_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                product_id NUMBER,
                product_name VARCHAR2(100),
                category VARCHAR2(50),
                price NUMBER(10,2),
                price_tier VARCHAR2(20),
                level_name VARCHAR2(20)
            )
            """
        )

        # Create Location Dimension with enriched attributes
        self.cursor.execute(
            """
            CREATE TABLE Location_Dim (
                location_dim_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                location_id NUMBER,
                city VARCHAR2(50),
                state VARCHAR2(50),
                country VARCHAR2(50),
                region VARCHAR2(50),
                level_name VARCHAR2(20)
            )
            """
        )

        # Enhanced Sales Fact Table with more metrics
        self.cursor.execute(
            """
            CREATE TABLE Sales_Fact (
                sales_fact_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                date_id NUMBER,
                customer_dim_id NUMBER,
                product_dim_id NUMBER,
                location_dim_id NUMBER,
                sale_date DATE,
                quantity NUMBER,
                total_amount NUMBER(10,2),
                discount_amount NUMBER(10,2),
                net_revenue NUMBER(10,2),
                FOREIGN KEY (customer_dim_id) REFERENCES Customer_Dim(customer_dim_id),
                FOREIGN KEY (product_dim_id) REFERENCES Product_Dim(product_dim_id),
                FOREIGN KEY (location_dim_id) REFERENCES Location_Dim(location_dim_id)
            )
            """
        )

        # Populate Date Dimension (last 2 years)
        self.cursor.execute(
            """
            INSERT INTO Date_Dim (date_id, full_date, year, quarter, month, day_of_week, is_weekend)
            SELECT 
                TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) as date_id,
                d as full_date,
                TO_NUMBER(TO_CHAR(d, 'YYYY')) as year,
                CEIL(TO_NUMBER(TO_CHAR(d, 'MM')) / 3) as quarter,
                TO_NUMBER(TO_CHAR(d, 'MM')) as month,
                TO_CHAR(d, 'Day') as day_of_week,
                CASE WHEN TO_CHAR(d, 'D') IN ('1','7') THEN 'Y' ELSE 'N' END as is_weekend
            FROM (
                SELECT TRUNC(SYSDATE) - (ROWNUM - 1) as d
                FROM DUAL CONNECT BY ROWNUM <= 730
            )
            """
        )

        # Populate Customer Dimension with enriched data
        self.cursor.execute(
            """
            INSERT INTO Customer_Dim (customer_id, first_name, last_name, email, phone, customer_level)
            SELECT 
                customer_id,
                first_name,
                last_name,
                email,
                phone,
                CASE 
                    WHEN customer_id <= 2 THEN 'Premium'
                    WHEN customer_id <= 3 THEN 'Gold'
                    ELSE 'Standard'
                END as customer_level
            FROM Customers
            """
        )

        # Populate Product Dimension with pricing tier
        self.cursor.execute(
            """
            INSERT INTO Product_Dim (product_id, product_name, category, price, price_tier, level_name)
            SELECT 
                product_id,
                product_name,
                category,
                price,
                CASE 
                    WHEN price >= 1000 THEN 'Premium'
                    WHEN price >= 300 THEN 'Standard'
                    WHEN price >= 50 THEN 'Economy'
                    ELSE 'Budget'
                END as price_tier,
                'DETAIL' as level_name
            FROM Products
            """
        )

        # Populate Location Dimension with region
        self.cursor.execute(
            """
            INSERT INTO Location_Dim (location_id, city, state, country, region, level_name)
            SELECT 
                location_id,
                city,
                state,
                country,
                CASE 
                    WHEN state IN ('NY', 'NJ', 'PA') THEN 'Northeast'
                    WHEN state IN ('CA', 'WA', 'OR') THEN 'West'
                    WHEN state IN ('TX', 'OK', 'LA') THEN 'South'
                    WHEN state IN ('IL', 'MI', 'OH') THEN 'Midwest'
                    ELSE 'Other'
                END as region,
                'DETAIL' as level_name
            FROM Locations
            """
        )

        # Populate Sales Fact with enriched metrics
        self.cursor.execute(
            """
            INSERT INTO Sales_Fact (date_id, customer_dim_id, product_dim_id, location_dim_id, sale_date, quantity, total_amount, discount_amount, net_revenue)
            SELECT
                TO_NUMBER(TO_CHAR(s.sale_date, 'YYYYMMDD')) as date_id,
                cd.customer_dim_id,
                pd.product_dim_id,
                ld.location_dim_id,
                s.sale_date,
                s.quantity,
                s.total_amount,
                ROUND(s.total_amount * 0.05, 2) as discount_amount,
                ROUND(s.total_amount * 0.95, 2) as net_revenue
            FROM Sales s
            JOIN Customer_Dim cd ON s.customer_id = cd.customer_id
            JOIN Product_Dim pd ON s.product_id = pd.product_id
            JOIN Location_Dim ld ON s.location_id = ld.location_id
            """
        )

        self.connection.commit()

    def create_sales_data_mart(self) -> None:
        self._safe_drop("DROP TABLE Sales_Data_Mart CASCADE CONSTRAINTS")

        self.cursor.execute(
            """
            CREATE TABLE Sales_Data_Mart (
                mart_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                product_name VARCHAR2(100),
                location_name VARCHAR2(100),
                total_quantity NUMBER,
                total_amount NUMBER(10,2),
                avg_sale_amount NUMBER(10,2),
                last_updated DATE DEFAULT SYSDATE
            )
            """
        )
        self.connection.commit()

    def populate_sales_data_mart(self) -> None:
        self.cursor.execute(
            """
            INSERT INTO Sales_Data_Mart
            (product_name, location_name, total_quantity, total_amount, avg_sale_amount)
            SELECT
                p.product_name,
                l.city || ', ' || l.state AS location_name,
                SUM(s.quantity) AS total_quantity,
                SUM(s.total_amount) AS total_amount,
                AVG(s.total_amount) AS avg_sale_amount
            FROM Sales s
            JOIN Products p ON s.product_id = p.product_id
            JOIN Locations l ON s.location_id = l.location_id
            GROUP BY p.product_name, l.city, l.state
            """
        )
        self.connection.commit()

    def get_performance_comparison(self) -> list[dict[str, Any]]:
        comparisons: list[dict[str, Any]] = []

        q1 = (
            """
            SELECT p.product_name, l.city, SUM(s.total_amount)
            FROM Sales s
            JOIN Products p ON s.product_id = p.product_id
            JOIN Locations l ON s.location_id = l.location_id
            GROUP BY p.product_name, l.city
            """,
            "OLTP Joins",
        )

        q2 = (
            """
            SELECT pd.product_name, ld.city, SUM(sf.total_amount)
            FROM Sales_Fact sf
            JOIN Product_Dim pd ON sf.product_dim_id = pd.product_dim_id
            JOIN Location_Dim ld ON sf.location_dim_id = ld.location_dim_id
            GROUP BY pd.product_name, ld.city
            """,
            "Star Schema",
        )

        q3 = (
            """
            SELECT product_name, location_name, total_amount
            FROM Sales_Data_Mart
            """,
            "Data Mart",
        )

        for sql, label in [q1, q2, q3]:
            self.cursor.execute(sql)
            plan_rows = self.cursor.fetchall()
            comparisons.append(
                {
                    "phase": label,
                    "rows_returned": len(plan_rows),
                    "note": "Compare elapsed time from API response timings in UI",
                }
            )

        return comparisons

    def fetch_all(self, sql: str) -> list[dict[str, Any]]:
        self.cursor.execute(sql)
        rows = self.cursor.fetchall()
        return self._rows_to_dicts(rows)

    def get_stats(self) -> dict[str, int]:
        stats = {}
        tables = [
            ("customers", "Customers"),
            ("products", "Products"),
            ("locations", "Locations"),
            ("sales", "Sales"),
            ("customer_dim", "Customer_Dim"),
            ("product_dim", "Product_Dim"),
            ("location_dim", "Location_Dim"),
            ("date_dim", "Date_Dim"),
            ("sales_fact", "Sales_Fact"),
            ("sales_datamart", "Sales_Data_Mart"),
        ]
        
        for key, table in tables:
            try:
                self.cursor.execute(f"SELECT COUNT(*) FROM {table}")
                count = int(self.cursor.fetchone()[0])
                stats[key] = count
            except oracledb.DatabaseError:
                stats[key] = 0
        
        # Add aggregated metrics
        try:
            self.cursor.execute("SELECT SUM(total_amount) FROM Sales")
            result = self.cursor.fetchone()
            stats["total_sales"] = int(result[0]) if result[0] else 0
        except:
            stats["total_sales"] = 0
        
        try:
            self.cursor.execute("SELECT COUNT(DISTINCT customer_id) FROM Sales")
            result = self.cursor.fetchone()
            stats["unique_customers"] = int(result[0]) if result[0] else 0
        except:
            stats["unique_customers"] = 0
        
        return stats
